# -*- coding: utf-8 -*-
"""MATPLOTLIB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VulwuRHilvZMNmzsAcOPKLyPngY37ZiV
"""

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='orange')
plt.plot(runs,w,color='orange')
plt.title('IndvsAus_score')
plt.show()

#generate array of 200 values between -pi and pi
tigar=np.linspace(-2*np.pi,2*np.pi,100)
print(tigar)

plt.plot(tigar,np.sin(tigar),color='black',label="hello")#sin plt.plot(z,y,color,labels....)
plt.title("sin(x)")
plt.legend(loc='best')
#display plot
plt.show()

#plotting all in one graph
# use : plt.legend(loc='best')
#plt.plot(x,y,color,label)
import numpy as np
import matplotlib.pyplot as plt
#creating x
overs = np.arange(5,50,5)
overs_a = np.arange(5,30,5)
#creating y
runs_i = np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wickets = np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color='blue',label='Indiaaaa')
plt.plot(overs_a,runs_a,color='yellow',label = 'Aus')
#combining two graphs
plt.legend(loc='best')
#displaying the final graph
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '3',label ='CompanyA',marker='.',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label ='CompanyB',marker = 'H')
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]

plt.subplot(2,1,1)
plt.plot(years,profit_b,color='black',linestyle='dotted',label ='CompanyB',marker = 'H')
plt.show()

import matplotlib.pyplot as plt
a = [230,560,780,127,128]
b = [200,160,270,127,400]
years = [1,2,3,4]
profit_a = [(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b = [(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '3',label ='CompanyA',marker='.',ms='15',mec='k')

plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
color=['yellow','green','blue','red']
plt.pie(a,labels = labe,colors=color)
plt.show()

#explode
a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.2,0,0,0]
plt.pie(a,labels = labe,explode = explo,startangle = 90)
plt.show()

a = np.array([25,60,5,10])
labe = ["AIML","Python","Pandas","Numpy"]
explo = [0.3,0,0,0]
plt.pie(a,labels = labe,explode = explo,shadow=True)
plt.legend()
plt.show()

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
tips=sns.load_dataset("tips")
print(tips)
#create a scatter plot
sns.scatterplot(x="total_bill",y="tip",data=tips,label='dots')
plt.title("Scatter Plot of Total")
plt.xlabel("Total BIll ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
iris=sns.load_dataset("iris")
#tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.scatterplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("Scatter Plot of Total")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.barplot(x="day",y="total_bill",data=tips)
plt.title("Scatter Plot of Total")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.boxplot(x="day",y="total_bill",data=tips)
plt.title("distribution of totla bill by day")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("distribution of totla bill by day")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

a=pd.read_csv("")
b=sns/lineplot(x='Passengers',y='Year',data=a)
plt.show()