# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W0i3C-PwXKyj5s-TN28O7J-bD4JrhUp5
"""

import pandas as pd
a=["Jwalitha",'ramya','Durga','Jahnavi','Lahari','Sunny','Dhanush']
r=pd.Series(a,index=[63,43,5,64,354,5,6])
print(r)

df=pd.read_csv("/content/grades_withnulls.csv")
print(df)

df=pd.read_csv("/content/grades_withnulls.txt")
print(df)

import pandas as pd
df=pd.read_excel("/content/grades_withnulls.xlsx")
print(df)

import pandas as pd
df=pd.read_excel("/content/grades_withnulls.xlsx",sheet_name=0)
print(df)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.head())
print(df.tail(n=10))

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.describe)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.describe().T)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.shape) #get the number of rows and columns
print(df.shape[0]) #get the number of rows only
print(df.shape[1]) # get the number of columns only

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df.columns)
l1=list(df.columns)
print(l1)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.head(7)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=0
df2.head(7)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.isnull().head(7)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.isnull().tail(7)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df2.isnull().sum())

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df2['SEM1'])

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df2[['SEM1','Grade']])

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df[df.index==1])

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df[df.index.isin(range(2,5))])

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df2.loc[1])

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
print(df2.loc[3])



import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[6:11,]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.loc[[10,2,7]]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.loc[10:15,['Names','Grade']]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.iloc[10:14,:3]#[row,column]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.loc[:7,['Names']] #[row,column]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df2.loc[df['Names']=='Rajesh']

df[df.Grade=='A']

df[df.SEM1 ==9.9]

df.loc[df['Grade']>'A',['Names']]

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
print(df)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df3=df2.copy()
df3

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")
df2=df.copy()
df3=df2.copy()
df3.dropna(inplace=True,axis=1)
print(df3)

import pandas as pd
df=pd.read_csv("/content/grades_withnulls.csv")#drops both rows and columns with Nan
df2=df.copy()
df3=df2.copy()
df3.dropna(inplace=True, how='all')
print(df3)

dfn=pd.read_csv("/content/grades_withnulls.csv")
dfn

mv=dfn['SEM1'].mean()
dfn=dfn.fillna(mv)
print(dfn)

dfn=dfn.drop_duplicates()
print(dfn)

dfn.rename(columns={'Grade':'GPA'},inplace=True)
dfn.head()

dfn.columns=['Student_name','Mr/Mrs','1stsem','2ndsem','3rdsem','F_Outcome','Placed?']
dfn.head()

dfn['Avg_score']=(dfn['1stsem']+dfn['2ndsem']+dfn['3rdsem'])/3
dfn.head()

dfn.groupby('Placed?').min()

dfn[['3rdsem','2ndsem']].plot.line()

"""#customize the color
#df[['BMI', 'Glucose']].plot.line(figsize=(20, 10), color={"BMI":
"red", "Glucose": "blue"})
"""

dfn.plot.line(subplots=True)