# -*- coding: utf-8 -*-
"""SEABORN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19myL65g5CGPh_MnvdtNR8efqxLEtAqcj
"""

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
tips=sns.load_dataset("tips")
print(tips)
#create a scatter plot
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("Scatter Plot of Total")
plt.xlabel("Total BIll ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
iris=sns.load_dataset("iris")
#tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.scatterplot(x="sepal_length",y="sepal_width",data=iris)
plt.title("Scatter Plot of Total")
plt.xlabel("sepal_length ($)")
plt.ylabel("sepal_width ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.barplot(x="day",y="total_bill",data=tips)
plt.title("Scatter Plot of Total")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.boxplot(x="day",y="total_bill",data=tips)
plt.title("distribution of totla bill by day")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example data set
#iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")
print(iris)
#create a scatter plot
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("distribution of totla bill by day")
plt.xlabel("Day of the Week")
plt.ylabel("Average total bill")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
a=pd.read_csv("/content/grades_withnulls.csv")
b=sns.lineplot(x='Names',y='SEM1',data=a)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
iris=sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("correlatin heatmap of iris dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
titanic= sns.load_dataset("titanic")
print(titanic)
#create a count plot
sns.countplot(x="class",data=titanic)
plt.title("passenger class disrtibution")
plt.xlabel("class")
plt.ylabel("count")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips=sns.load_dataset("tips")

sns.lmplot(x="total_bill",y="tip",data=tips)
plt.title("djdj")
plt.xlabel("Total bill ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
#load example dataset
titanic= sns.load_dataset("titanic")
print(titanic)
#create a count plot
g=sns.FacetGrid(titanic,col="class")
g.map(sns.histplot,"age")
plt.subplots_adjust(top=0.8)
g.fig.suptitle("age dist")
plt.show()

